analyzer_rules: # 分析类型的规则
  - unused_declaration
  - unused_enumerated
  - unused_import
  - explicit_self

disabled_rules: # 执行时排除掉的规则
  - identifier_name
  - type_name

opt_in_rules: # 一些规则仅仅是可选的
  - implicitly_unwrapped_optional

excluded: # 执行 linting 时忽略的路径。 优先级比 `included` 更高。
  - Carthage
  - Pods
  - R.generated.swift

# 可配置的规则可以通过这个配置文件来自定义
# 二进制规则可以设置他们的严格程度
force_cast: warning # 隐式
force_try:
  severity: warning # 显式
# 同时有警告和错误等级的规则，可以只设置它的警告等级
# 隐式
line_length: 200



reporter: "xcode"